name: Deploy Vite app to GitHub Pages

on:
  push:
    branches:
      - main   # se activa cada vez que hagas push a main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -- --base=/

      - name: Create SPA fallback (404.html)
        run: cp dist/index.html dist/404.html

      - name: Disable Jekyll
        run: touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: zakariaconcepts.com   # tu dominio custom
